### ISSUE TITLE
Tried to add my image url in JSONStruct payload                      "      \"imageurl\" : \"https://photos.google.com/photo/AF1QipNvQWszNT0GMbXKUGGMdQ_WkIbmfQTF6CLs39tU"\n" +

### ISSUE THREAD

**Issue by maheshmobile** [wwdablu/SimplyPDF#24]
2021-10-13 10:17:28.704 4709-4709/? E/simplypdfsampl: Unknown bits set in runtime_flags: 0x8000
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
2021-10-13 10:17:28.704 4709-4709/? E/simplypdfsampl: Unknown bits set in runtime_flags: 0x8000
2021-10-13 10:17:28.704 4709-4709/? E/simplypdfsampl: Unknown bits set in runtime_flags: 0x8000
2021-10-13 10:17:31.755 4709-4709/com.wwdablu.soumya.simplypdfsample E/pdf :: com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
    java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0x80000000)
     call GlideException#logRootCauses(String) for more detail

**Comment by maheshmobile** [comment]
my image url is https://photos.google.com/photo/AF1QipNvQWszNT0GMbXKUGGMdQ_WkIbmfQTF6CLs39tU and code is

package com.wwdablu.soumya.simplypdfsample;

public class JSONStruct {

    public static final String payload = "{\n" +
            "  \"contents\" : [\n" +
            "    {\n" +
            "      \"type\" : \"text\",\n" +
            "      \"content\" : \"Mahesh - Mobile App Developer, KOC\",\n" +
            "      \"properties\" : {\n" +
            "        \"size\" : 24,\n" +
            "        \"color\" : \"#000000\",\n" +
            "        \"underline\" : true,\n" +
            "        \"strikethrough\" : false\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"image\",\n" +
            "      \"imageurl\" : \"https://photos.google.com/photo/AF1QipNvQWszNT0GMbXKUGGMdQ_WkIbmfQTF6CLs39tU\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"shape\",\n" +
            "      \"shape\" : \"circle\",\n" +
            "      \"radius\" : 50,\n" +
            "      \"properties\" : {\n" +
            "        \"linecolor\" : \"#000000\",\n" +
            "        \"linewidth\" : 1,\n" +
            "        \"shouldfill\" : true\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"shape\",\n" +
            "      \"shape\" : \"box\",\n" +
            "      \"width\" : 100,\n" +
            "      \"height\" : 50,\n" +
            "      \"properties\" : {\n" +
            "        \"linecolor\" : \"#000000\",\n" +
            "        \"linewidth\" : 1,\n" +
            "        \"shouldfill\" : true\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"newpage\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"shape\",\n" +
            "      \"shape\" : \"freeform\",\n" +
            "      \"points\" : [\n" +
            "        {\n" +
            "          \"line\" : [0,0]\n" +
            "        },\n" +
            "        {\n" +
            "          \"line\" : [100, 0]\n" +
            "        },\n" +
            "        {\n" +
            "          \"line\" : [100,100]\n" +
            "        },\n" +
            "        {\n" +
            "          \"line\" : [0,0]\n" +
            "        }\n" +
            "      ],\n" +
            "      \"properties\" : {\n" +
            "        \"linecolor\" : \"#FF0000\",\n" +
            "        \"linewidth\" : 4,\n" +
            "        \"shouldfill\" : true\n" +
            "      }\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"space\",\n" +
            "      \"height\" : 25\n" +
            "    },\n" +
            "    {\n" +
            "      \"type\" : \"table\",\n" +
            "      \"contents\" : [\n" +
            "        {\n" +
            "          \"row\" : [\n" +
            "            {\n" +
            "              \"type\" : \"text\",\n" +
            "              \"content\" : \"Version\",\n" +
            "              \"width\" : 50,\n" +
            "              \"properties\" : {\n" +
            "                \"size\" : 12,\n" +
            "                \"color\" : \"#000000\",\n" +
            "                \"underline\" : false,\n" +
            "                \"strikethrough\" : false\n" +
            "              }\n" +
            "            },\n" +
            "            {\n" +
            "              \"type\" : \"text\",\n" +
            "              \"content\" : \"1.1.0\",\n" +
            "              \"width\" : 50,\n" +
            "              \"properties\" : {\n" +
            "                \"size\" : 12,\n" +
            "                \"color\" : \"#000000\",\n" +
            "                \"underline\" : false,\n" +
            "                \"strikethrough\" : false\n" +
            "              }\n" +
            "            }\n" +
            "          ]\n" +
            "        },\n" +
            "        {\n" +
            "          \"row\" : [\n" +
            "            {\n" +
            "              \"type\" : \"text\",\n" +
            "              \"content\" : \"Source code is available in GitHub\",\n" +
            "              \"width\" : 100,\n" +
            "              \"properties\" : {\n" +
            "                \"size\" : 18,\n" +
            "                \"color\" : \"#0000FF\",\n" +
            "                \"underline\" : false,\n" +
            "                \"strikethrough\" : false\n" +
            "              }\n" +
            "            }\n" +
            "          ]\n" +
            "        }\n" +
            "      ],\n" +
            "      \"properties\" : {\n" +
            "        \"width\" : 1,\n" +
            "        \"color\" : \"#000000\"\n" +
            "      }\n" +
            "    }\n" +
            "  ]\n" +
            "}";
}

**Comment by maheshmobile** [comment]
ok
